POST https://cgpscmitra.herokuapp.com/posts
Content-Type: application/json

{
    "postedBy":3,
    "title": "now or never post",
    "description": "dont wait for magic to happen"
}

###

GET https://cgpscmitra.herokuapp.com/posts?from=6&limit=8

###

http://cgpscmitra.herokuapp.com/posts

###

GET https://cgpscmitra.herokuapp.com/posts/4

###